### ISSUE TITLE
purefb_s3user maximum keys reached warning logic

### ISSUE THREAD

**Issue by winstonpickle** [Pure-Storage-Ansible/FlashBlade-Collection#104]
key_count in purefb_s3user is always 0 if not importing a key. The logic to warn the Maximum Access Key count is then never reached. "key_count += 1" is within "if module.params['imported_key']:"

**Comment by sdodsley** [comment]
Yes - good catch - there is a slight indentation issue. 
This fix is in PR #105

**Comment by sdodsley** [comment]
Resolved - will be in the next Collection release
