### ISSUE TITLE
purefb_dns module throws a TypeError if 'search' is None on the Array DNS settings

### ISSUE THREAD

**Issue by jake2184** [Pure-Storage-Ansible/FlashBlade-Collection#106]
**Describe the bug**
Running the purefb_dns module against a cluster without 'search' defined results in an Ansible error

**To Reproduce**
1. Have a clear 'search' path for an Array
2. Attempt to update this using the purefb_dns module

**Additional context**

```
if sorted(module.params['search']) != sorted(current_dns.items[0].search):
```
This line, purefb_dns.py:147 ,  needs a clause to either check if current_dns.items[0].search is none, or give a default value of []. Currently if `current_dns.items[0].search` is `None`, because it hasn't been defined, `sorted()` throws a TypeError as None is not iterable.

I did not experience this with a new cluster installed at Purity/FB 2.4.11, but met it after having the cluster upgraded to 3.0.9.

**Comment by jake2184** [comment]
Actually this looks like it might be more of an issue with how current_dns is populated - after fixing the module and running it myself, it does not have an idempotent result - after successfully posting the DNS parameters, on a subsequent run Ansible still has `current_dns.items[0].search` as None

**Comment by sdodsley** [comment]
Thanks for catching this. We'll get a bug fix created this week ready for the next release

**Comment by sdodsley** [comment]
Can you confirm your version of Ansible and the version of the FlashBlade Collection you are running?

**Comment by jake2184** [comment]
FlashBlade Collection: v1.4.0
Ansible: 2.10.1 (venv)

**Comment by sdodsley** [comment]
Addressed in #108

**Comment by jake2184** [comment]
That fixes the TypeError thrown - but that was a side effect of an underlying issue.

I don't think the Pure is correctly updating/returning the search path. This occurs with this python module after applying #108, but can also be reproduced with curl. 


Can you relay this back/investigate further? Otherwise please let me know if I should raise a case through the Support Portal. 

```
jreynolds@laptop ~$ cat data 
{
 "domain": "internal",
 "nameservers": ["10.11.12.5"],
 "search": ["internal", "test.internal", "test2.internal"]
}

jreynolds@laptop ~$ curl -s -H "Content-Type: application/json" "Accept: application/json" -H "x-auth-token: 1234567"  https://myarray.example.com/api/1.9/dns/ -XPATCH -d @data | python3 -m json.tool

{
    "items": [
        {
            "name": "myarray",
            "domain": "internal",
            "nameservers": [
                "10.11.12.5"
            ],
            "search": null
        }
    ]
}

jreynolds@laptop ~$ curl -s -H "Content-Type: application/json" "Accept: application/json" -H "x-auth-token: 1234567"  https://myarray.example.com/api/1.9/dns/ | python3 -m json.tool

{
    "pagination_info": {
        "total_item_count": 1,
        "continuation_token": null
    },
    "items": [
        {
            "name": "myarray",
            "domain": "internal",
            "nameservers": [
                "10.11.12.5"
            ],
            "search": null
        }
    ]
}


```

**Comment by sdodsley** [comment]
@jake2184 Yes - I see the issue now - I think there is a major issue in the REST API endpoint. I'm raising this with the appropriate engineering team.
In the interim, we will have to disable this particular parameter in the DNS module

**Comment by sdodsley** [comment]
@jake2184 Quick response from our Engineering team - this is a deprecated feature so I will be removing it from the DNS module. Sorry for the confusion

**Comment by jake2184** [comment]
Understood - not a problem, I don't need the functionality so will remove it.
