### ISSUE TITLE
purefb_ds module always reports changed as True

### ISSUE THREAD

**Issue by jake2184** [Pure-Storage-Ansible/FlashBlade-Collection#110]
**Describe the bug**
purefb_dsrole always reports "changed = True" even when no change is made

**To Reproduce**
1. Create a role, with state = present
2. Run ansible repeatedly. changed is always true

**Additional context**
Due to purefb_dsrole.py:99.

This conditional needs pushing inside of the inner if clause in the update function. Whilst you're there, you should also push  the check_mode conditional within the current inner if clause, so 'changed' is correctly reported in check mode.

**Comment by sdodsley** [comment]
Closed by #111

**Comment by jake2184** [comment]
This commit only half fixes the issue - you have missed the part I highlighted in the initial issue above.

The module will still always report changed as true when in check mode - this can lead to a lot of unnecessary debugging when a user is trying to work out why the module is reporting that it wants to make a change (when it doesn't really)

**Comment by sdodsley** [comment]
Check mode is implemented in all Pure modules to return a simple true. 
There is a plan to update all modules to fullysupport check_mode but this is still some time away.
