### ISSUE TITLE
Missing param purefb_lifecycle

### ISSUE THREAD

**Issue by winstonpickle** [Pure-Storage-Ansible/FlashBlade-Collection#122]
It appears purefb_lifecycle is missing a param when attempting to create a lifecycle policy. bucket is required by LifecycleRulePost but not send causing the error below.  `bucket=module.params["bucket"]` resolves this and the policy is then created as expected.

 `The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_purestorage.flashblade.purefb_lifecycle_payload_6O7b8E/ansible_purestorage.flashblade.purefb_lifecycle_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_lifecycle.py", line 156, in create_rule
  File "/usr/lib/python2.7/site-packages/purity_fb/purity_fb_1dot10/models/lifecycle_rule_post.py", line 61, in __init__
    self.bucket = bucket
  File "/usr/lib/python2.7/site-packages/purity_fb/purity_fb_1dot10/models/lifecycle_rule_post.py", line 89, in bucket
    raise Val**u**eError("Invalid value for `bucket`, must not be `None`")  # noqa: E501
failed: [arrayname] (item={'key': u'policyname', 'value': {u'keep_for': u'2d'}}) => {
    "ansible_loop_var": "bucket_policy",
    "bucket_policy": {
        "key": "policyname",
        "value": {
            "keep_for": "2d"
        }
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "bucket": "bucketname",
            "enabled": true,
            "fb_url": "192.168.0.1",
            "keep_for": "2d",
            "name": "policyname",
            "prefix": null,
            "state": "present"
        }
    },
    "msg": "Failed to create lifecycle rule policyname for bucket bucketname."`

**Comment by sdodsley** [comment]
@winstonpickle can you provide details on the Purity version of your FlashBlade and an example of the failing task in a yaml file. 
Also, please confirm the version of Ansible and FlashBlade Collection you are using.

**Comment by sdodsley** [comment]
Looks like I found the bug - thanks for reporting it.
