### ISSUE TITLE
Modules do not support the --diff flag

### ISSUE THREAD

**Issue by jake2184** [Pure-Storage-Ansible/FlashBlade-Collection#148]
Most (if not all) of the plugin modules here do not present a diff. 

This can make it difficult to safely assess/use the module to maintain systems. For instance, after updating the collection, the fs module applied a change to every filesystem I had - but there was no way to know what this change was. Similarly it means --check mode cannot be sensibly used to asses changes before applying them.

I've created a sample PR to demonstrate how this could be fixed. If the validity of the concept can be evaluated, then I can formalise the PR/stretch the concept to other modules.

**Comment by sdodsley** [comment]
@jake2184 can you rebase your PR #149 so that the latest fix for `purefb_fs` is included
