### ISSUE TITLE
create_v2_connection() function fails in creating connection between 2 REST 2 capable arrays

### ISSUE THREAD

**Issue by anhopure** [Pure-Storage-Ansible/FlashBlade-Collection#182]
**Describe the bug**
Running the ansible playbook for filesystem_replication.yml ([link](https://github.com/PureStorage-OpenConnect/ansible-playbook-examples/blob/master/flashblade/pure-fb-filesystem-replication/roles/purefb_filesystem_replication/tasks/replication.yml)), we get a failure in creating a v2 connection between two REST 2 capable arrays. On a cluster that does not have any replica links configured, bandwidth throttling is not set. But in the code, we see that it is trying to set the flashblade.TimeWindow. See line 276 in the screen shot.
![Screen Shot 2022-03-07 at 12 15 27 PM](https://user-images.githubusercontent.com/86134650/157111009-a0b7b850-7217-4097-924f-2ffe4a8be0b7.png)

**To Reproduce**
1. Run the ansible-playbook for filesystem_replication.yml:
**ansible-playbook filesystem_replication.yml -e "env=region"**
2. You will see the failure when running the task: 
**# Create replication
- name: Create remote credential and replica link for {{ repl_loop.key }}
  block:
  - name: replication | Create a connection from {{ repl_vars.src.fb_name }} to remote FlashBlade {{ repl_vars.dst.fb_name }} server
    purefb_connect:
      state: present
      target_url: "{{ dst_fb_url }}"
      target_api: "{{ dst_fb_token }}"
      fb_url: "{{ src_fb_url }}"
      api_token: "{{ src_fb_token }}**
3. In the playbook.log, you will see this error reported:
**line 276, in create_v2_connection\n  File \"/tmp/ansible_purefb_connect_payload_vlzqabt8/ansible_purefb_connect_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_connect.py\", line 146, in _convert_to_millisecs\nTypeError: 'NoneType' object is not subscriptable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1**

**Configuration:**
Ansible: 2.10.17
FlashBlade Collection: 
purestorage.flashblade    1.3.0
purestorage.flashblade 1.9.0

**Comment by sdodsley** [comment]
Acknowldeged. Will work on this as soon as possible

**Comment by sdodsley** [comment]
@anhopure can you try this patch to see if it resolves your issue?

**Comment by anhopure** [comment]
> @anhopure can you try this patch to see if it resolves your issue?

Yes, I tested out the patch and it works in my setup.
