### ISSUE TITLE
Got error when using purestorage.flashblade.purefb_policy to create or list policy

### ISSUE THREAD

**Issue by fatghosts** [Pure-Storage-Ansible/FlashBlade-Collection#189]
**Describe the bug**
Use example code to create new policy successfully at the first time, but it produce error when run second time without changing the code.

**To Reproduce**
source code "get-policy.yaml": 
- name: Ansible FlashBlade Demo
  hosts: localhost
  collections:
  - purestorage.flashblade
  tasks:
  - name: List existng ruser access policies
    purefb_policy:
      account: object-store-test-account1
      name: object-store-ploicy
      fb_url: 172.31.157.66
      api_token: T-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      rule: rw
      policy_type: access
      actions: "s3:*"
      object_resources: "*"

1. Run playbook: "ansible-playbook get-policy.yaml"
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Ansible FlashBlade Demo] *******************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [localhost]

TASK [List existng ruser access policies] ********************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

2. Run the same playbook again: "ansible-playbook get-policy.yaml"
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Ansible FlashBlade Demo] *******************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [localhost]

TASK [List existng ruser access policies] ********************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: update_os_policy() takes 2 positional arguments but 3 were given
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/anuser/.ansible/tmp/ansible-tmp-1658381850.7977161-3248305-139910670681846/AnsiballZ_purefb_policy.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/anuser/.ansible/tmp/ansible-tmp-1658381850.7977161-3248305-139910670681846/AnsiballZ_purefb_policy.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/anuser/.ansible/tmp/ansible-tmp-1658381850.7977161-3248305-139910670681846/AnsiballZ_purefb_policy.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.purestorage.flashblade.plugins.modules.purefb_policy', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_purefb_policy_payload_bv1ndi4i/ansible_purefb_policy_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_policy.py\", line 1697, in <module>\n  File \"/tmp/ansible_purefb_policy_payload_bv1ndi4i/ansible_purefb_policy_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_policy.py\", line 1613, in main\nTypeError: update_os_policy() takes 2 positional arguments but 3 were given\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Expected behavior**
When run the script second time, it should check the policy exist and exit with xml as other module.

**Desktop (please complete the following information):**
 - OS: redhat 7.9

**Comment by sdodsley** [comment]
Please try #190 to see if this resolves your issues
