### ISSUE TITLE
Can't configure a snapshot policy with multiple rules via ansible

### ISSUE THREAD

**Issue by screamingwalls** [Pure-Storage-Ansible/FlashBlade-Collection#198]
I'd like to create in ansible a snapshot policy with multiple rules, like this:

> purepolicy snapshot rule list local
Name   Every  At  Time Zone  Keep For
local  1h     -   -          8h
       1d     -   -          1w
       1w     -   -          2w

There doesn't seem to be a way to do this in purefb_policy right now.  Only a single every or keep_for parameter is allowed - if you specify multiple parameters, only the last one takes effect.   Specifying multiple tasks with the same policy name has a similar effect - only the last one takes effect.

Maybe the fix is to have the every/at/keep_for parameters accept a list of strings, not just a singe string, similar to how the filesystem parameter works, and each element in the list would represent one rule.

**Comment by sdodsley** [comment]
@screamingwalls Can you provide examples of this failing?
You have to use a unique `rule` name for each policy, otherwise it will get overwritten.

**Comment by screamingwalls** [comment]
I can't provide an example of a failure, since the ansible syntax doesn't allow me to represent this.  The only ansible I've tried will successfully create a single policy with a single rule but it will never create a single policy with three rules.

The flashblade configuration (via the gui and the cli) allows for a single snapshot policy to contain multiple rules - all with the same name (the same policy).  For example, on the flashblade I can create a policy named "local" with three rules, as follows:

>purepolicy snapshot create local
purepolicy snapshot rule add --keep-for '8h' --every '1h' local
purepolicy snapshot rule add --keep-for '1w' --every '1d' local
purepolicy snapshot rule add --keep-for '2w' --every '1w' local

This results in a single policy containing three rules that looks like this:

>\> purepolicy snapshot rule list local
Name Every At Time Zone Keep For
local 1h - - 8h
1d - - 1w
1w - - 2w

I don't see any way in the current purefb_policy module  to create this type of policy with three rules, even though flashblade supports it.

**Comment by sdodsley** [comment]
@screamingwalls OK - I understand now. I'll get this looked into and come up with a fix as soon as possible.
