### ISSUE TITLE
Cannot set the http proxy to use "http" instead of "https"

### ISSUE THREAD

**Issue by screamingwalls** [Pure-Storage-Ansible/FlashBlade-Collection#199]
**Is your feature request related to a problem? Please describe.**
I want to use a proxy that only accepts "http" and not "https", but I can't configure the  flashblade to use "http" via ansible.

**Describe the solution you'd like**
I'd like a way for purefb_proxy to allow "http" as a scheme.

**Describe alternatives you've considered**
Avoiding ansible for configuration of the flashblade.

**Additional context**
If I use purefb_proxy as follows it will always set the scheme to "https" even though the flashblade itself allows "http" as a valid scheme.  So, this is a limitation of the purefb_proxy ansible module, not of the flashblade itself, since the flashblade can be configured, without ansible, to use "http" as a scheme.

- name: Configure http proxy
  purefb_proxy:
    host: "{{http_proxy_host}}"
    port: "{{http_proxy_port}}"

**Comment by sdodsley** [comment]
Agreed. Will fix.

**Comment by sdodsley** [comment]
@screamingwalls #200 should fix this
