### ISSUE TITLE
purestorage.flashblade.purefb_bucket parameter not set

### ISSUE THREAD

**Issue by JoshuaHaus** [Pure-Storage-Ansible/FlashBlade-Collection#265]
**Describe the bug**
Parameters like object_lock_enabled: true  and retention_lock: retcheted are not setted after Playbook runs on success

**To Reproduce**
1. Run a playbook with Parameters called above and versioning: enabled
2. Playbook will fail with error message:
"Object Store Bucket playbooktest-playbooktest6 creation failed. Error: Combination of object lock freeze locked objects \"false\" and versioning \"none\" is invalid"
3. Run a playbook with splitted tasks: First Task versioning: enabled - 2nd Task versioning: enabled, object_lock_enabled: true  and retention_lock: retcheted
4. Both tasks run successfully. Versioning is enabled in the finished bucket. but object lock is disabled and retention_lock is setted to unlocked

**Expected behavior**
versioning is enabled
object Lock is enabled
retention Lock is Retchated

**Additional context**
Tryied ansible Collection 1.15.0, 1.14.0, 1.13.1, 1.12.1

**Comment by JoshuaHaus** [comment]
We are running on Purity//FB 4.3.4

**Comment by sdodsley** [comment]
@JoshuaHaus I have worked on the bucket module to fix the issue, but also to allow you to create the bucket with the config you want in one command.
You no longer have to create the bucket with versioning and then call again for retention and object lock.
This can all be done in one call now.
Please let me know if this fix works for you.

**Comment by JoshuaHaus** [comment]
@sdodsley Is there a new Release with this bug fix or have you updated the current release 1.15.0?

**Comment by sdodsley** [comment]
This fix is not incorporated into any release as yet.

It will be in the next release once you confirm the patch works as expected.

We will hold the next release until we receive your confirmation.

Simon

| *Simon Dodsley DD MBCS CITP* |  Director, Open Source Integrations
| Pure Storage, Inc. | +1 (510) 516-2682
| ***@***.*** | www.purestorage.com

*BOOK TIME WITH ME*: 30 minutes
<https://purestorage.chilipiper.com/book/me/simon-dodsley?type=my-meeting>

[image: http://www.purestorage.com/_media/header_logo.png?130529]

**Comment by JoshuaHaus** [comment]
@sdodsley I have tested localy with the current master branch and have to say, that nothing has changed to version 1.15.0 I get the same error message when I try to do all Changes in One Task and nothing changes, when splitting the tasks. Only Versioning is enabled. The other to paramaters aren't set properly

**Comment by sdodsley** [comment]
@JoshuaHaus have you applied the patch #267 as this has the changes to purefa_bucket.py that fix the issue

**Comment by JoshuaHaus** [comment]
I have missed the patch. 

I now get an other error:

Error: The quota_limit for a bucket must be between 1 byte and 9.22 exabytes.

but we didn't want to set a quota for the bucket and there for havn't set that paramater

**Comment by JoshuaHaus** [comment]
The quota value isn't required and shouldn't be set due to the advise from Veeam

**Comment by sdodsley** [comment]
@JoshuaHaus i have updated the patch to fix the problem. Quota not required.

**Comment by JoshuaHaus** [comment]
works for me
