### ISSUE TITLE
Playbook Task failed when deleting policy

### ISSUE THREAD

**Issue by JoshuaHaus** [Pure-Storage-Ansible/FlashBlade-Collection#278]
**Describe the bug**
when deleting a Policy with purestorage.flashblade.purefb_policy the error message:
"py-pure-client sdk is required for this module" appears. 

py-pure-client sdk is installed on the executing server. 

This is the Task in the Ansible playbook:
 - name: Delete a object store access policy FlashbladeA
    delegate_to: {{delegationhost}}
    become: true
    purestorage.flashblade.purefb_policy:
      name: "policy-{{survey_fbbuucketname}}"
      policy_type: access
      account: "{{ survey_fbaccname }}"
      state: absent
      fb_url: {{flashbladeURL}}
      api_token: "{{flashbladeToken}}"

The Policy I try to Delete has no assigned user

**To Reproduce**
1. Create a policy
2. try to delete policy with Ansible
3. See error

**Expected behavior**
The policy is deleted

**Screenshots**
![image](https://github.com/Pure-Storage-Ansible/FlashBlade-Collection/assets/161033581/936dbab7-7e56-48ad-9396-e37e3b7a9565)

**Comment by sdodsley** [comment]
@JoshuaHaus this is caused because you do not have the latest `py-pure-client` installed.
Please upgrade to the latest version and the issue will be resolved.

**Comment by JoshuaHaus** [comment]
Thanks alot. 

After updating py-pure-client it worked as planned.
