### ISSUE TITLE
Unable to set access_control

### ISSUE THREAD

**Issue by Breemskin** [Pure-Storage-Ansible/FlashBlade-Collection#290]
**Describe the bug**
Apologies if I'm just being an idiot here, but I'm unable to set access control when SMB is selected as the protocol. 

  - name: Create filesystem
    purefb_fs:
      api_token: "{{ api_token }}"
      fb_url: "{{ flashblade_name }}"
      size: "{{ share_cap }}"
      name: "{{ share_name }}"
      smb: true
      nfsv3: false
      nfsv4: false
      policy: "{{ policy_name }}"
      policy_state: present
      access_control: smb
      safeguard_acls: false

Set to false:
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to create filesystem test_fs. Error: ACL safeguarding cannot be disabled when the access control style is \"smb\"."}

Set to true:
fatal: [localhost]: FAILED! => {"changed": false, "msg": "ACL Safeguarding cannot be enabled with SMB or if access_control is mode-bits or independent."}

**Expected behavior**
I would expect to be able to set the access control to SMB and then choose whether to enable safeguarding or not, the UI lets me do both.

**Comment by sdodsley** [comment]
@Breemskin i agree this doesn't seem correct. Those error messages seem to be coming from the API response from the array. Let us do some investigation. It may just be a workflow/logic error

**Comment by sdodsley** [comment]
@Breemskin please try patch #291 to see if this resolves your issues.

**Comment by Breemskin** [comment]
> @Breemskin please try patch #291 to see if this resolves your issues.

That's great. I have tried it and safeguarding must be enabled (which is fine) and access_control now sets to smb. Thank you!
