### ISSUE TITLE
Errors when attempting to use "import" function of purefb_certs

### ISSUE THREAD

**Issue by tylergmuir** [Pure-Storage-Ansible/FlashBlade-Collection#297]
**Describe the bug**
When trying to use `state=import`, there is an error reported of `TypeError: __init__() got an unexpected keyword argument 'passphrase'`

**To Reproduce**
1. Use `purestorage.flashbalde.purefb_certs`
2. Set `state` to `import`.
3. Run playbook

**Expected behavior**
The certificate should be imported.

**Additional context**
This seems to be a difference between the `CertificatePost` method from purity_fb vs the FlashBlade client in py-pure-client.

**Comment by sdodsley** [comment]
@tylergmuir can you see if this patch resolves your problem?

**Comment by sdodsley** [comment]
@tylergmuir not sure what happened there. Please try again.

**Comment by tylergmuir** [comment]
@sdodsley Your PR does fix my issue. Thanks!
