### ISSUE TITLE
Update Ansible Collection Documentation to include py-pure-client

### ISSUE THREAD

**Issue by utf18** [Pure-Storage-Ansible/FlashBlade-Collection#312]
**Describe the bug**
The Ansible Collection Documentation requirements does not include the py-pure-client
Installation of the collection does succeed, but running it produces an error such as: "flashblade is not defined"

**To Reproduce**
(https://docs.ansible.com/ansible/latest/collections/purestorage/flashblade/purefb_s3acc_module.html#requirements)

**Expected behavior**
All requirements for the module are displayed

**Additional context**
the dependency is existent in the github module, just missing in the ansible documentation

**Comment by sdodsley** [comment]
Correct - fixed in associated PR. Will be reflected in ansible docs site when next ansible release is built and released.

**Comment by utf18** [comment]
thx :)
