### ISSUE TITLE
disable an existing access key

### ISSUE THREAD

**Issue by JoshuaHaus** [Pure-Storage-Ansible/FlashBlade-Collection#335]
**Is your feature request related to a problem? Please describe.**
We would like to have the posibility to disable the access key for a specific user and reenable it to a later time again.

**Describe the solution you'd like**
an additional paramater like access_key_is_enabled as boolean with true as default in the module purefb_s3user

**Describe alternatives you've considered**
no alternative solution yet

**Additional context**
<img width="1581" alt="{9F53D6A3-92C7-4317-A051-E0FBD57FCF7D}" src="https://github.com/user-attachments/assets/16a27732-b687-4417-8b70-30dea7ef48a9">
<img width="1228" alt="{04761D90-FF84-4E01-B6B3-CD2FF14809C9}" src="https://github.com/user-attachments/assets/8b04128c-0d47-4d27-b55f-cdd3af3964cb">

**Comment by sdodsley** [comment]
We will look at adding this for the next collection release

**Comment by sdodsley** [comment]
@JoshuaHaus I have updated the S3 modules that control accounts and users, including access keys, to allow you to change the state of any access key.
Please check out #338 and see if these changes do what you need.

**Comment by JoshuaHaus** [comment]
@sdodsley Changes are looking godd to me
