### ISSUE TITLE
Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [Pure-Storage-Ansible/FlashBlade-Collection#34]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of https://github.com/ansible-collection-migration/purestorage.flashblade against this repo

In particular:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

##### ISSUE TYPE
- Bug Report

**Comment by sdodsley** [comment]
@gundalow I assume it is no longer required to action this issue

**Comment by gundalow** [comment]
It would be worth checking out both repos and doing a file-level diff between them both

**Comment by sdodsley** [comment]
I am a little confused as to why your repo exists. It will have diverged significantly from the latest versions we have.
I thought, correct me if I'm wrong, that as we have already claimed our modules Ansible would just point to our repo

**Comment by gundalow** [comment]
https://github.com/ansible-collection-migration/purestorage.flashblade is archived (read only).

**Comment by sdodsley** [comment]
Assuming this is not needed now
